[[Reactant]]
arch = "x86_64"
cuda_version = "none"
cxxstring_abi = "cxx11"
git-tree-sha1 = "471133b4291efc4f0884c981e47fa4997c3de62a"
gpu = "none"
lazy = true
libc = "glibc"
mode = "opt"
os = "linux"

    [[Reactant.download]]
    sha256 = "26c896f76c8141e82043d66b2f44253e8918caab5c8c6784eca4e60f2296bbfe"
    url = "https://github.com/JuliaBinaryWrappers/Reactant_jll.jl/releases/download/Reactant-v0.0.131+0/Reactant.v0.0.131.x86_64-linux-gnu-cxx11-cuda_version+none-gpu+none-mode+opt.tar.gz"
[[Reactant]]
arch = "aarch64"
cuda_version = "none"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f23fe81465a977a156bf663930af765b8b3d9a8e"
gpu = "none"
lazy = true
libc = "glibc"
mode = "opt"
os = "linux"

    [[Reactant.download]]
    sha256 = "5f4d4a16f34fa909846897441dc3ff387233a86b7e8f1b94ac76c4564363ae68"
    url = "https://github.com/JuliaBinaryWrappers/Reactant_jll.jl/releases/download/Reactant-v0.0.131+0/Reactant.v0.0.131.aarch64-linux-gnu-cxx11-cuda_version+none-gpu+none-mode+opt.tar.gz"
[[Reactant]]
arch = "x86_64"
cuda_version = "none"
git-tree-sha1 = "e593a7e06d271766da608b0a074e1c82ff6f3a70"
gpu = "none"
lazy = true
mode = "opt"
os = "macos"

    [[Reactant.download]]
    sha256 = "47eced21150cb7afc46ec03471d85e1f127afb4f69a79fc72a0f323f0742c3cc"
    url = "https://github.com/JuliaBinaryWrappers/Reactant_jll.jl/releases/download/Reactant-v0.0.131+0/Reactant.v0.0.131.x86_64-apple-darwin-cuda_version+none-gpu+none-mode+opt.tar.gz"
[[Reactant]]
arch = "aarch64"
cuda_version = "none"
git-tree-sha1 = "df5bb015e96e5ea33a8252e4e0ef43704479b9b5"
gpu = "none"
lazy = true
mode = "opt"
os = "macos"

    [[Reactant.download]]
    sha256 = "3f82ee41f859949933ee3575f45ae9f6e59f8d364cf1c40d7ddbc3b40e274f69"
    url = "https://github.com/JuliaBinaryWrappers/Reactant_jll.jl/releases/download/Reactant-v0.0.131+0/Reactant.v0.0.131.aarch64-apple-darwin-cuda_version+none-gpu+none-mode+opt.tar.gz"
[[Reactant]]
arch = "x86_64"
cuda_version = "none"
git-tree-sha1 = "ecb48f4334716d24d24338a90d4e20953cede8af"
gpu = "none"
lazy = true
mode = "dbg"
os = "macos"

    [[Reactant.download]]
    sha256 = "626fd10933d72966531fef2e30756226fdfe6b806624fa833d1f48819b065108"
    url = "https://github.com/JuliaBinaryWrappers/Reactant_jll.jl/releases/download/Reactant-v0.0.131+0/Reactant.v0.0.131.x86_64-apple-darwin-cuda_version+none-gpu+none-mode+dbg.tar.gz"
[[Reactant]]
arch = "aarch64"
cuda_version = "none"
git-tree-sha1 = "429d143b0c5b0cbf481012a2134fe61ce59315a2"
gpu = "none"
lazy = true
mode = "dbg"
os = "macos"

    [[Reactant.download]]
    sha256 = "ffabb55eba8d5645631aec85642154aae399a5a79efe574c77b488233c6a5d8b"
    url = "https://github.com/JuliaBinaryWrappers/Reactant_jll.jl/releases/download/Reactant-v0.0.131+0/Reactant.v0.0.131.aarch64-apple-darwin-cuda_version+none-gpu+none-mode+dbg.tar.gz"
[[Reactant]]
arch = "x86_64"
cuda_version = "12.1"
cxxstring_abi = "cxx11"
git-tree-sha1 = "432881d8dffc42a49d59621bd2d64026528aed0d"
gpu = "cuda"
lazy = true
libc = "glibc"
mode = "opt"
os = "linux"

    [[Reactant.download]]
    sha256 = "b8879a62df7a7ccdf249d24f5fc9ced1e6f6e88ae571372c4ce5ad21d7597898"
    url = "https://github.com/JuliaBinaryWrappers/Reactant_jll.jl/releases/download/Reactant-v0.0.131+0/Reactant.v0.0.131.x86_64-linux-gnu-cxx11-cuda_version+12.1-gpu+cuda-mode+opt.tar.gz"
[[Reactant]]
arch = "x86_64"
cuda_version = "12.4"
cxxstring_abi = "cxx11"
git-tree-sha1 = "31f3f2eb55d0008adb2d93751a0148dead5a351c"
gpu = "cuda"
lazy = true
libc = "glibc"
mode = "opt"
os = "linux"

    [[Reactant.download]]
    sha256 = "63f8fdf0e624bc22e7782943edb87ab8b205d74df1fc28b585619fe59b4d2d7d"
    url = "https://github.com/JuliaBinaryWrappers/Reactant_jll.jl/releases/download/Reactant-v0.0.131+0/Reactant.v0.0.131.x86_64-linux-gnu-cxx11-cuda_version+12.4-gpu+cuda-mode+opt.tar.gz"
[[Reactant]]
arch = "aarch64"
cuda_version = "12.4"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1023e2bb18765d49be765acc121e37a9c4a84127"
gpu = "cuda"
lazy = true
libc = "glibc"
mode = "opt"
os = "linux"

    [[Reactant.download]]
    sha256 = "89d5f6ef58d9519c491d38553dfbe4a4f691cbc79b63c6680dbf16bfbc38ad35"
    url = "https://github.com/JuliaBinaryWrappers/Reactant_jll.jl/releases/download/Reactant-v0.0.131+0/Reactant.v0.0.131.aarch64-linux-gnu-cxx11-cuda_version+12.4-gpu+cuda-mode+opt.tar.gz"
[[Reactant]]
arch = "x86_64"
cuda_version = "12.6"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cf0487ce3a26395ec07fff8dda104d9206994a39"
gpu = "cuda"
lazy = true
libc = "glibc"
mode = "opt"
os = "linux"

    [[Reactant.download]]
    sha256 = "ca225e701eaa06a03671d4e012018579a71b21fc4d0efd8563006965fcc63b82"
    url = "https://github.com/JuliaBinaryWrappers/Reactant_jll.jl/releases/download/Reactant-v0.0.131+0/Reactant.v0.0.131.x86_64-linux-gnu-cxx11-cuda_version+12.6-gpu+cuda-mode+opt.tar.gz"
[[Reactant]]
arch = "aarch64"
cuda_version = "12.6"
cxxstring_abi = "cxx11"
git-tree-sha1 = "83929e9cc33f8a1c4de674c63d788052729732a0"
gpu = "cuda"
lazy = true
libc = "glibc"
mode = "opt"
os = "linux"

    [[Reactant.download]]
    sha256 = "72af90463c65cf400279b18cae00f7217bbf16e1fc91d9d6e4712a7026051d3e"
    url = "https://github.com/JuliaBinaryWrappers/Reactant_jll.jl/releases/download/Reactant-v0.0.131+0/Reactant.v0.0.131.aarch64-linux-gnu-cxx11-cuda_version+12.6-gpu+cuda-mode+opt.tar.gz"
